import fs from 'fs';
import { execSync } from 'child_process';

try {
    // 1. Read package.json
    const pkg = JSON.parse(fs.readFileSync('./package.json', 'utf8'));
    let version = pkg.version || '1.2.0';

    // 2. Increment the patch version
    const parts = version.split('.').map(Number);
    if (parts.length === 3 && !isNaN(parts[2])) {
        parts[2] += 1;
        version = parts.join('.');
    } else {
        version = '1.2.1';
    }

    // Write the incremented version back to package.json
    pkg.version = version;
    fs.writeFileSync('./package.json', JSON.stringify(pkg, null, 2) + '\n', 'utf8');

    // 3. Get latest Git commit short hash
    let gitHash = 'local';
    try {
        gitHash = execSync('git rev-parse --short HEAD').toString().trim();
    } catch (e) {
        console.warn('Could not read Git hash, using fallback.');
    }

    // 4. Generate version.js
    const versionStr = `v${version}-${gitHash}`;
    const codeContent = `// Automatically generated by version-updater.js during build\nexport const APP_VERSION = '${versionStr}';\n`;
    fs.writeFileSync('./version.js', codeContent, 'utf8');

    console.log(`Successfully updated app version to: ${versionStr}`);
} catch (error) {
    console.error('Failed to update version:', error);
    process.exit(1);
}
